### PR TITLE
DUPLO-15896 : No Kubernetes cluster for this plan" error should be displayed when the provided plan does not have EKS or GKE cluster

### PR DESCRIPTION
**Pull request by Duplo-nikv**
## Overview

Error output fix for data-source of duplocloud_eks_credentials/duplocloud_gke_credentials
## Summary of changes

This PR does the following:

- conditional logic change at error level
- ...

## Testing performed

- [ ] Using unit tests
- [ ] Manually, on my local system
- [ ✓] Manually, on a remote test system

## Describe any breaking changes

- ...

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-15896 TF: duplocloud_gke_credentials/duplocloud_eks_credentials Datasource: "No Kubernetes cluster for this plan" error should be displayed when the provided plan does not have EKS or GKE cluster enabled.](https://app.clickup.com/t/8655600/DUPLO-15896)

**Review by tahir-duplo — APPROVED** [review]
LGTM

**Comment by tahir-duplo** [comment]
Please resolve conflicts and merge @Duplo-nikv

**Review by tahir-duplo — APPROVED** [review]
LGTM

**Pull request merged**
