### PR TITLE
Duplo 8942/dynamo table updates

### PR DESCRIPTION
**Pull request by mick-duplocloud**
## Overview

... (don't forget to put your clickup ticket ID in the title) ...

## Summary of changes

This PR does the following:

- ...
- ...

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

___

## **Type**
enhancement, bug_fix

___

## **Description**
- Added a new function `tagDynamoDBtTableV2` to handle tagging of DynamoDB tables.
- Updated the `resourceAwsDynamoDBTableUpdateV2` function to include tagging and enhanced conditional logic for various table settings like point-in-time recovery and deletion protection.
- Introduced changes to handle deletion protection as a pointer to support conditional updates.
- Implemented new API methods in the SDK for tagging resources and updating SSE specifications and deletion protection settings in isolation, adhering to AWS SDK constraints.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>resource_duplo_aws_dynamodb_table_v2.go</strong><dd><code>Enhance DynamoDB Table Update and Tagging Logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
duplocloud/resource_duplo_aws_dynamodb_table_v2.go

<li>Added function to tag DynamoDB tables.<br> <li> Enhanced update logic for DynamoDB tables to handle point-in-time <br>recovery, deletion protection, SSE specification, and throughput <br>updates.<br> <li> Updated boolean assignment to pointer for deletion protection.<br>

</details>
    

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/515/files#diff-589167a86b500ce20842028a24b38988f35a3d0719a3f4ddd018599bc8c2008a">+52/-18</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>aws_dynamo_db.go</strong><dd><code>Add DynamoDB Tagging and Isolated Update Methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
duplosdk/aws_dynamo_db.go

<li>Added structs and methods for tagging DynamoDB resources.<br> <li> Added methods for updating SSE specification and deletion protection <br>as isolated updates.<br>

</details>
    

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/515/files#diff-560bfcccfc9ca280a8ada5717b4f6af16e0a02937f90c7caedbd20bc58abfe99">+55/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-8942 TF: Implement missing dynamodb v2 update](https://app.clickup.com/t/8655600/DUPLO-8942)

**Comment by sp1676** [comment]
/'update_changelog --pr_update_changelog.push_changelog_changes=true'

**Review by tahir-duplo — APPROVED** [review]
LGTM

**Pull request merged**
