### PR TITLE
DUPLO-11669: dynamodb tabl v2 - add point in recovery and delete protection config

### PR DESCRIPTION
**Pull request by pravin-duplocloud**
## Overview

DUPLO-11669: TF: Add delete_protection_enabled and point_in_time_recovery for dynamodb table v2 resource

## Summary of changes

This PR does the following:

- add  delete_protection_enabled
- add support for point_in_time_recovery

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [X] Manually, on a remote test system

## Describe any breaking changes

- None

___

## **Type**
enhancement

___

## **Description**
- Added support for configuring deletion protection (`deletion_protection_enabled`) and point in time recovery (`is_point_in_time_recovery`) for DynamoDB tables.
- Implemented functionality to enable point in time recovery during table creation.
- Updated the SDK to support new DynamoDB table configurations.
- Updated documentation and changelog to reflect the new features.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>resource_duplo_aws_dynamodb_table_v2.go</strong><dd><code>Add Deletion Protection and Point in Time Recovery Support for </code><br><code>DynamoDB Table</code></dd></summary>
<hr>
      
duplocloud/resource_duplo_aws_dynamodb_table_v2.go

<li>Added support for <code>deletion_protection_enabled</code> and <br><code>is_point_in_time_recovery</code> in DynamoDB table schema.<br> <li> Implemented setting point in time recovery during table creation.<br> <li> Updated resource read function to include new attributes.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/417/files#diff-589167a86b500ce20842028a24b38988f35a3d0719a3f4ddd018599bc8c2008a">+37/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>aws_dynamo_db.go</strong><dd><code>SDK Support for DynamoDB Table Deletion Protection and Point in Time </code><br><code>Recovery</code></dd></summary>
<hr>
      
duplosdk/aws_dynamo_db.go

<li>Introduced <code>DeletionProtectionEnabled</code> and <code>PointInTimeRecoveryStatus</code> in <br><code>DuploDynamoDBTableV2</code>.<br> <li> Added <code>DuploDynamoDBTableV2TimeInRecovery</code> and <br><code>DuploDynamoDBTableV2ContinuousBackupsDescription</code> structs.<br> <li> Implemented <code>DynamoDBTableV2PointInRecovery</code> API call.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/417/files#diff-560bfcccfc9ca280a8ada5717b4f6af16e0a02937f90c7caedbd20bc58abfe99">+63/-25</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CHANGELOG.md</strong><dd><code>Update Changelog with DynamoDB Table Enhancements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
CHANGELOG.md

<li>Documented the addition of deletion protection and point in time <br>recovery for DynamoDB tables.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/417/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>aws_dynamodb_table_v2.md</strong><dd><code>Document Deletion Protection and Point in Time Recovery for DynamoDB </code><br><code>Tables</code></dd></summary>
<hr>
      
docs/resources/aws_dynamodb_table_v2.md

<li>Updated documentation to include <code>deletion_protection_enabled</code> and <br><code>is_point_in_time_recovery</code> attributes.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/417/files#diff-119c98c4cd93c70ceab159cbe3658633fc99b839f5f3d73224c10fd3cba2a458">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-11669 TF: Add delete_protection_enabled and point_in_time_recovery for dynamodb table v2 resource](https://app.clickup.com/t/8655600/DUPLO-11669)

**Comment by joek-duplo** [comment]
/update_changelog --pr_update_changelog.push_changelog_changes=true

**Review by joek-duplo — CHANGES_REQUESTED** [review]
Please fix the changelog, it is adding a duplicate date, and make sure it refers to the TF resource by name.

**Comment by joek-duplo** [comment]
/update_changelog --pr_update_changelog.push_changelog_changes=true

**Comment by pravin-duplocloud** [comment]
> Please fix the changelog, it is adding a duplicate date, and make sure it refers to the TF resource by name.

done

**Review by joek-duplo — DISMISSED** [review]

**Pull request merged**
