### PR TITLE
DUPLO-2983, DUPLO-3066, and DUPLO-2982 fixed.

### PR DESCRIPTION
**Pull request by tahir-duplo**
DUPLO-2983, DUPLO-3066, and DUPLO-2982 fixed.

https://app.clickup.com/t/8655600/DUPLO-2983
https://app.clickup.com/t/8655600/DUPLO-2982
https://app.clickup.com/t/8655600/DUPLO-3066

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-2983 Lily : LB Configuration Deprecate backend protocol field and add Backend Protocol version or policy field](https://app.clickup.com/t/8655600/DUPLO-2983)

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-2982 Lambda function update should use full_name, currently name is used and since there is no such function update is failing](https://app.clickup.com/t/8655600/DUPLO-2982)

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-2982 Lambda function update should use full_name, currently name is used and since there is no such function update is failing](https://app.clickup.com/t/8655600/DUPLO-2982)

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-3066 Spotnana : Metadata support in duplocloud_plan_settings resource](https://app.clickup.com/t/8655600/DUPLO-3066)

**Review by joek-duplo — APPROVED** [review]

**Pull request merged**
