### PR TITLE
DUPLO-8942 Dynamo Table Update

### PR DESCRIPTION
**Pull request by mick-duplocloud**
## Overview

Updated code to prefix DynamoDB table names only when `"ENABLEAWSRESOURCEMGMTUSINGTAGS"` is set to true.

## Summary of changes

 Removed broken API call. Made call to system for dynamic resource prefixing.

This PR does the following:

- commented out broken API call.
- Added call to get system settings.

## Testing performed

- [ ] Using unit tests
- [X] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

- ...

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-8942 TF: Implement missing dynamodb v2 update](https://app.clickup.com/t/8655600/DUPLO-8942)

**Review by Duplo-nikv — COMMENTED** [review]
Throwing below error
 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to duplocloud_aws_dynamodb_table_v2.tst-dynamodb-table, provider "provider[\"registry.terraform.io/duplocloud/duplocloud\"]" produced
│ an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Review by tahir-duplo — APPROVED** [review]
LGTM

**Comment by tahir-duplo** [comment]
@mick-duplocloud Can you please fix conflicts.

**Pull request closed without merging**
