### PR TITLE
DUPLO-11564 add metadata service option to example

### PR DESCRIPTION
**Pull request by ddiaz-duplo**
## Change description

add metadata service example

### Development

- [x] Pull requests may not be submitted to the *master* branch (use *develop* instead) - or they will be closed.
- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer.
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by joek-duplo — CHANGES_REQUESTED** [review]
The ticket requested that the metadata service option be added.  But it did not request that the `OsDiskSize` option be removed.

**Comment by ddiaz-duplo** [comment]
I removed OsDiskSize from there because there are 2 examples and OsDiskSize is in the other one https://github.com/duplocloud/terraform-provider-duplocloud/blob/develop/examples/resources/duplocloud_aws_host/resource.tf#L18C2-L18C2S
But I can add it to this one if you prefer as well

**Comment by ddiaz-duplo** [comment]
@joek-duplo I added the field you requested

**Review by joek-duplo — APPROVED** [review]
you are right.  I read your PR too fast! 

approving and merging.

**Pull request merged**
