### PR TITLE
DUPLO-13077 fixes broken elastic search creation with no dedicated master type and fixes elasticsearch_version mapping

### PR DESCRIPTION
**Pull request by Matheusbafutto**
## Overview

Creation of Elastic search cluster was crashing when `dedicated_master_type` field of cluster config was not defined because it was implicitly being assigned `{ Value: null }` by Go. The unexpected structure made AWS throw a non descriptive error message `Value cannot be null, parameter : key`. This PR makes this field into a pointer so we may properly assign it `null` when it is not defined. AWS lets us create it properly with no errors if dedicated_master_type is null.

This PR also fixes attribute mapping between API response and TF state. The correct version field is called `EngineVerion` instead of `ElasticSearchVersion`.

## Summary of changes

This PR does the following:

- Makes `dedicated_master_type` into a pointer so it is null if absent from parameters when creating `DuploElasticSearchDomainRequest`
- fixes mapping between `elsaticsearch_version` and the BE's `EngineVersion` fields

## Testing performed

- [ ] Using unit tests
- [x] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

- ...

___

## **Type**
bug_fix

___

## **Description**
- Fixed a potential crash in `duplocloud_aws_elasticsearch` creation when `dedicated_master_type` was not defined by changing `DedicatedMasterType` to a pointer.
- Updated `DuploElasticSearchDomainClusterConfig` to handle null values for `DedicatedMasterType` more gracefully.
- Documented the fix in the CHANGELOG.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>resource_duplo_aws_elasticsearch.go</strong><dd><code>Fix ElasticSearch Creation with Undefined `dedicated_master_type`</code></dd></summary>
<hr>
      
duplocloud/resource_duplo_aws_elasticsearch.go

<li>Changed <code>DedicatedMasterType</code> from <code>DuploStringValue</code> to a pointer of <br><code>DuploStringValue</code> to handle null values correctly.<br> <li> Ensured <code>dedicated_master_type</code> is assigned correctly when creating <br><code>DuploElasticSearchDomainRequest</code>.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/416/files#diff-74075534ff698afe18f26ee1215cb2f57c76aa949aca23c1464f4dcaed02386f">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>aws_elasticsearch.go</strong><dd><code>Update `DedicatedMasterType` to Pointer for Null Handling</code></dd></summary>
<hr>
      
duplosdk/aws_elasticsearch.go

<li>Modified <code>DedicatedMasterType</code> in <code>DuploElasticSearchDomainClusterConfig</code> <br>to be a pointer to handle null values.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/416/files#diff-aa10acb1bd1e5bbc66aecf2b5383547b4724d45bfeab0c654a8b9f61148dcf61">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CHANGELOG.md</strong><dd><code>Update CHANGELOG for ElasticSearch Creation Fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
CHANGELOG.md

<li>Added entry for fixing crash in <code>duplocloud_aws_elasticsearch</code> creation <br>when <code>dedicated_master_type</code> was not defined.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/416/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-13077 Terraform Provider - Elasticsearch/Opensearch cluster continuously flagged for destroy/recreate](https://app.clickup.com/t/8655600/DUPLO-13077)

**Comment by Matheusbafutto** [comment]
I guess @Duplo-nikv fixed the mapping before me [here](https://github.com/duplocloud/terraform-provider-duplocloud/pull/411). Good thing I uncovered this dedicated master bug so this work wont have been for nothing :)

**Comment by Matheusbafutto** [comment]
@komalkadam-dc You did something very similar to this in [this PR](https://github.com/duplocloud/terraform-provider-duplocloud/pull/394). would you review this too?

**Review by joek-duplo — COMMENTED** [review]
TF changelogs must specify the resource name.

**Review by joek-duplo — DISMISSED** [review]

**Pull request merged**
