### PR TITLE
DUPLO-26529: TF: Terraform state is corrupted sometimes [rate exceeded error]

### PR DESCRIPTION
**Pull request by pravin-duplocloud**
## Overview

DUPLO-26529: TF: Terraform state is corrupted sometimes

## Summary of changes

This PR does the following:

- handle rate exceed  for large number of dynamodbs

## Testing performed

- [ ] Using unit tests
- [x] Manually, on my local system
- [x] Manually, on a remote test system

## Describe any breaking changes

- ...

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-26529 TF: Terraform state is corrupted sometimes](https://app.clickup.com/t/8655600/DUPLO-26529)

**Comment by pravin-duplocloud** [comment]
image

**Comment by pravin-duplocloud** [comment]
image

**Comment by pravin-duplocloud** [comment]
image

**Review by tahir-duplo — APPROVED** [review]
LGTM

**Pull request merged**
