### PR TITLE
DUPLO-15208 - Fix issue where SkipFinalSnapshot is not included in the JSON on update.

### PR DESCRIPTION
**Pull request by sum-duplocloud**
## Overview

DUPLO-15208

## Summary of changes

This PR does the following:

- Update how DuploRdsUpdateInstance is serialized.
- Fix issue where SkipFinalSnapshot is not included in TF update.

## Testing performed

- [ ] Using unit tests
- [x] Manually, on my local system
- [x] Manually, on a remote test system

## Describe any breaking changes

- none

___

## **Type**
bug_fix

___

## **Description**
- Fixed an issue where `SkipFinalSnapshot` was not always included in the JSON serialization during RDS instance updates. This change ensures that `SkipFinalSnapshot` is always serialized, affecting both `DuploRdsUpdateInstance` and `DuploRdsUpdateCluster` structs.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>rds_instance.go</strong><dd><code>Ensure SkipFinalSnapshot is Always Serialized</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
duplosdk/rds_instance.go

<li>Changed <code>SkipFinalSnapshot</code> field to always be included in JSON <br>serialization for both <code>DuploRdsUpdateInstance</code> and <br><code>DuploRdsUpdateCluster</code> structs.<br>

</details>
    

  </td>
  <td><a href="https:/duplocloud/terraform-provider-duplocloud/pull/421/files#diff-3aeb597ae11ae40342366a786a3b78f55a1265ea03d8d2729401d9a7f3b7291a">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-15208 TF: RDS: Final snapshot update is not working, Terraform plan and apply display modifications for attribute but attribute value is not getting updated](https://app.clickup.com/t/8655600/DUPLO-15208)

**Comment by joek-duplo** [comment]
/update_changelog --pr_update_changelog.push_changelog_changes=true

**Review by joek-duplo — CHANGES_REQUESTED** [review]
TF resource changelogs must include the resource name.

**Review by joek-duplo — DISMISSED** [review]

**Pull request merged**
