### PR TITLE
DUPLO-21238 chore: port rds perf insights to read replica resource and DUPLO-21184 Fix

### PR DESCRIPTION
**Pull request by Matheusbafutto**
## Overview

Introduces performance insights as configurable properties to read replica rds resources in terraform provider

## Summary of changes

This PR does the following:

- Applies performance insight configuration to read replica TF resource

## Testing performed

- [ ] Using unit tests
- [x] Manually, on my local system
- [ ] Manually, on a remote test system

## Describe any breaking changes

No

## Sanity Checking

tested delete, create and update 

Primary disabled and replica enabled
image
image

Primary enabled and read replica disabled
image
image

Primary and replica perf insights config enabled
image
image

Primary and erplica perf insights config disabled
image

image

___

### **PR Type**
Enhancement, Documentation

___

### **Description**
- Introduced performance insights as a configurable feature for RDS read replicas, enhancing database performance monitoring.
- Implemented logic to enable and manage performance insights for both primary and read replica RDS instances.
- Updated documentation and examples to reflect the new performance insights feature.
- Added a constant for the RDS DocumentDB engine to improve code readability and maintainability.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>resource_duplo_rds_instance.go</strong><dd><code>Enable and manage performance insights for RDS instances</code>&nbsp; </dd></summary>
<hr>

duplocloud/resource_duplo_rds_instance.go

<li>Added logic to enable performance insights for RDS instances.<br> <li> Introduced waiting mechanism for performance insights to be enabled.<br> <li> Updated engine checks to use a constant for DocumentDB.<br>

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-a8bf9b56a3e9b39899a5d37d7608110678908754e0848fab2d0320653ea65f71">+47/-15</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>resource_duplo_rds_read_replica.go</strong><dd><code>Add performance insights to RDS read replicas</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

duplocloud/resource_duplo_rds_read_replica.go

<li>Added performance insights configuration for read replicas.<br> <li> Implemented update logic for performance insights.<br> <li> Introduced waiting mechanism for read replica availability.<br>

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-1ffdcfb6fc7a0fed517c0f77bbfb406b208cb1084f420e755eb9d029683dfdfe">+154/-3</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>rds_instance.go</strong><dd><code>Update RDS instance struct for performance insights</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

duplosdk/rds_instance.go

- Changed `EnablePerformanceInsights` to non-optional.

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-3aeb597ae11ae40342366a786a3b78f55a1265ea03d8d2729401d9a7f3b7291a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>utils.go</strong><dd><code>Define constant for RDS DocumentDB engine</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

duplocloud/utils.go

- Defined constant for RDS DocumentDB engine.

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-a8b0d524e2d08c8969f058ead081e31847409515b2417bfcbfcdf83cf79a1b9e">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>CHANGELOG.md</strong><dd><code>Update changelog for performance insights feature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

CHANGELOG.md

- Documented addition of performance insights for RDS read replicas.

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed">+8/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>rds_read_replica.md</strong><dd><code>Document performance insights for RDS read replicas</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/resources/rds_read_replica.md

<li>Added examples and documentation for performance insights.<br> <li> Detailed nested schema for performance insights.<br>

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-e223dad9b259eae20181173087aafb1d47d2eb221d1a7d6ba1493bd78aafc5af">+99/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>resource.tf</strong><dd><code>Add examples for RDS read replica performance insights</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

examples/resources/duplocloud_rds_read_replica/resource.tf

- Added examples for enabling performance insights on read replicas.

</details>

  </td>
  <td><a href="https://github.com/duplocloud/terraform-provider-duplocloud/pull/701/files#diff-3e5f9986f926543549bd2d58be9bb79a2277e56293965198b698e94a55e4d9ff">+88/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-21238 TF:RDS: Add support of performance_insights to read replica resource](https://app.clickup.com/t/8655600/DUPLO-21238)

**Comment by Matheusbafutto** [comment]
Merge https://github.com/duplocloud-internal/duplo/pull/3149 first

**Review by Duplo-nikv — APPROVED** [review]
LGTM

**Review by Duplo-nikv — APPROVED** [review]
Add example and updated documentation

**Comment by zafarabbas** [comment]
Task linked: [DUPLO-21184 TF: RDS:DocDB: not able to enable Performance Insight, duplo gives fault for not supported while aws supports](https://app.clickup.com/t/8655600/DUPLO-21184)

**Review by zafarabbas — APPROVED** [review]

**Pull request merged**
